[workspace]
resolver = "2"
members = [
    "mandelbrot",
    "watch",
    "loader",
    "compile-in-memory",
]

[profile.dev]
opt-level = 1

[patch.crates-io.num-traits]
git = "https://github.com/zachs18/num-traits.git"
branch = "f128"
