[package]
name = "compile-in-memory"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2"
loader = { path = "../loader", default-features = false }

[dev-dependencies]
num-complex = "*"
