[package]
name = "mandelbrot"
version = "0.2.0"
edition = "2021"

[profile.dev]
opt-level = 1

[dependencies]
image = "0.24"
num-complex = "0.4"
gtk = "0.15"
blocking = "1.2"

[dependencies.watch]
package = "watch"
path = "../watch"

[build-dependencies]
gio = "0.15"
