[package]
name = "mandelbrot"
version = "0.2.0"
edition = "2021"

[features]
custom_fractals = []

[dependencies]
image = "0.24"
num-complex = "0.4"
gtk = "0.15"
blocking = "1.2"
num-traits = "0.2.15"
f128 = "0.2.9"

[dependencies.watch]
package = "watch"
path = "../watch"

[build-dependencies]
gio = "0.15"
